### ISSUE TITLE
Is this NLTK's nltk.pos_tag?

### ISSUE THREAD

**Issue by alvations** [arne-cl/nltk-maxent-pos-tagger#1]
There's a recent question: http://stackoverflow.com/questions/31386224/what-created-maxent-treebank-pos-tagger-english-pickle

I'm also interested to know is the pickle file from `nltk.pos_tag` from this repo? If so, could you help give more details on the SO question.

Thanks in advance!!

**Comment by arne-cl** [comment]
Dear alvations,

I am sorry for answering that late, I must have missed github's reminder email.

I don't think that `nltk` used my module to generate their model.
I wrote this in 2008 as a class project. Back then, a maximum entropy based pos tagger was listed as a [project idea](http://web.archive.org/web/20090123230819/http://www.nltk.org/projects) on the nltk website.

I wanted to contribute the code, but the process was too intimidating (Google Code, SVN etc.) for me.
